<main>
    <form action="index.php?route=check-connexion" method="post">
            <div>
                <label for="email">Email:</label>
                <input type="email" name="email" id="email">
            </div>
            <div>
                <label for="password">Password:</label>
                <input type="password" name="password" id="password">
            </div>
    
            <button type="submit">Connexion</button>
    </form>
</main>