<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8" />
		<title>Exercice Routeur MVC</title>
	</head>
	<body>
		<header>
			<nav>
				<ul>
					<li>
						<a href="index.php">Accueil</a>
					</li>
					<li>
						<a href="index.php?route=connexion">connection</a>
					</li>
                    <li>
						<a href="index.php?route=inscrption">Inscription</a>
					</li>
				</ul>
			</nav>
		</header>
		<?php
			// votre code ici
            require "./controllers/AuthController.php";
		?>
	</body>
</html>